[package]
name = "logicx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.5", features = ["nightly", "csr"] }
backtrace = "0.3.74"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"